<?PHP

$extAliases = array(
 'cycle',
 'button',
 'splitbutton',
 'chart',
 'component', 'box',
 'viewport',
 'buttongroup',
 'container',
 'coolpanel',
 'cool',
 'draw',
 'editor',
 'flash',
 'checkboxgroup',
 'label',
 'radiogroup',
 'form',
 'htmleditor',
 'radiofield', 'radio',
 'pickerfield',
 'checkboxfield', 'checkbox',
 'textareafield', 'textarea',
 'filefield', 'fileuploadfield',
 'searchfield',
 'field',
 'combobox', 'combo',
 'customspinner',
 'spinnerfield',
 'displayfield',
 'timefield',
 'datefield',
 'textfield',
 'customtrigger',
 'triggerfield', 'trigger',
 'hiddenfield', 'hidden',
 'numberfield',
 'fieldset',
 'fieldcontainer',
 'propertygrid',
 'headercontainer',
 'paginggridscroller',
 'gridcolumn',
 'booleancolumn',
 'datecolumn',
 'templatecolumn',
 'numbercolumn',
 'actioncolumn',
 'gridscroller',
 'gridpanel', 'grid',
 'rownumberer',
 'gridview',
 'image', 'imagecomponent',
 'loadmask',
 'menucheckitem',
 'menuseparator',
 'colormenu',
 'menu',
 'datemenu',
 'menuitem',
 'tool',
 'panel',
 'tablepanel',
 'header',
 'monthpicker',
 'colorpicker',
 'timepicker',
 'datepicker',
 'progressbar',
 'splitter',
 'multislider',
 'slidertip',
 'slider', 'sliderfield',
 'tab',
 'tabpanel',
 'tabbar',
 'tooltip',
 'tbseparator',
 'tbspacer',
 'toolbar',
 'tbitem',
 'tbfill',
 'pagingtoolbar',
 'tbtext',
 'treecolumn',
 'treepanel',
 'treeview',
 'tableview',
 'boundlist',
 'dataview',
 'window',
 'messagebox',
);


?>
