<?PHP

$extAliases = array(
  'widget.image', 'widget.imagecomponent',
  'widget.loadmask',
  'widget.progressbar',
  'widget.progressbarwidget',
  'widget.tbfill',
  'widget.tbitem',
  'widget.tbseparator',
  'widget.button',
  'widget.toolbar',
  'widget.panel',
  'widget.tip',
  'widget.tooltip',
  'widget.quicktip',
  'widget.displayfield',
  'widget.tablepanel',
  'widget.dataview',
  'widget.tableview',
  'widget.gridview',
  'widget.gridpanel', 'widget.grid',
  'widget.checkboxfield', 'widget.checkbox',
  'widget.bindinspector-componentdetail',
  'widget.treeview',
  'widget.headercontainer',
  'widget.treecolumn',
  'widget.treepanel',
  'widget.textfield',
  'widget.bindinspector-componentlist',
  'widget.bordersplitter',
  'widget.tab',
  'widget.tabpanel',
  'widget.bindinspector-viewmodeldetail',
  'widget.bindinspector-container',
  'widget.window',
  'widget.splitbutton',
  'widget.cycle',
  'widget.buttongroup',
  'widget.viewport',
  'widget.flash',
  'widget.textareafield', 'widget.textarea',
  'widget.messagebox',
  'widget.fieldcontainer',
  'widget.checkboxgroup',
  'widget.fieldset',
  'widget.label',
  'widget.form',
  'widget.radiofield', 'widget.radio',
  'widget.radiogroup',
  'widget.pickerfield',
  'widget.tbtext',
  'widget.spinnerfield',
  'widget.numberfield',
  'widget.boundlist',
  'widget.combobox', 'widget.combo',
  'widget.monthpicker',
  'widget.datepicker',
  'widget.datefield',
  'widget.filebutton',
  'widget.filefield', 'widget.fileuploadfield',
  'widget.hiddenfield', 'widget.hidden',
  'widget.colorpicker',
  'widget.htmleditor',
  'widget.timepicker',
  'widget.timefield',
  'widget.triggerfield', 'widget.trigger',
  'widget.roweditorbuttons',
  'widget.roweditor',
  'widget.actioncolumn',
  'widget.booleancolumn',
  'widget.checkcolumn',
  'widget.datecolumn',
  'widget.numbercolumn',
  'widget.rownumberer',
  'widget.templatecolumn',
  'widget.widgetcolumn',
  'widget.menuitem',
  'widget.menucheckitem',
  'widget.menuseparator',
  'widget.menu',
  'widget.propertygrid',
   'widget.colormenu',
   'widget.datemenu',
  'widget.slidertip',
  'widget.multislider',
  'widget.slider', 'widget.sliderfield',
  'widget.sliderwidget',
  'widget.sparklinebar',
  'widget.sparklinebox',
  'widget.sparklinebullet',
  'widget.sparklinediscrete',
  'widget.sparklineline',
  'widget.sparklinepie',
  'widget.sparklinetristate',
  'widget.tbspacer',
);


?>
