<?PHP

$extAliases = array(
  'animation.cube',
  'animation.fade', 'animation.fadeIn',
  'animation.fade', 'animation.fadeIn',
  'animation.fadeOut',
  'animation.flip',
  'animation.pop', 'animation.popIn',
  'animation.pop', 'animation.popIn',
  'animation.popOut',
  'animation.slide', 'animation.slideIn',
  'animation.slide', 'animation.slideIn',
  'animation.slideOut',
  'animation.slideOut',
  'box.overflow.menu',
  'box.overflow.Menu',
  'box.overflow.none',
  'box.overflow.None',
  'box.overflow.scroller',
  'box.overflow.Scroller',
  'data.field.auto',
  'data.field.bool',
  'data.field.boolean',
  'data.field.date',
  'data.field.float',
  'data.field.int',
  'data.field.integer',
  'data.field.number',
  'data.field.string',
  'data.identifier.default',
  'data.identifier.negative',
  'data.identifier.sequential',
  'data.identifier.uuid',
  'data.operation.create',
  'data.operation.destroy',
  'data.operation.read',
  'data.operation.update',
  'data.validator.base',
  'data.validator.bound',
  'data.validator.email',
  'data.validator.exclusion',
  'data.validator.format',
  'data.validator.inclusion',
  'data.validator.length',
  'data.validator.list',
  'data.validator.presence',
  'data.validator.range',
  'direct.event',
  'direct.exception',
  'direct.jsonprovider',
  'direct.pollingprovider',
  'direct.provider',
  'direct.remotingprovider',
  'direct.rpc',
  'direct.transaction',
  'easing.ease-in',
  'easing.ease-out',
  'easing.linear',
  'editing.editing',
  'feature.abstractsummary',
  'feature.feature',
  'feature.grouping',
  'feature.groupingsummary',
  'feature.rowbody',
  'feature.summary',
  'formaction.directload',
  'formaction.directsubmit',
  'formaction.load',
  'formaction.standardsubmit',
  'formaction.submit',
  function(object, methodName) {
  'fx.layout.card.cover',
  'fx.layout.card.cube',
  'fx.layout.card.fade',
  'fx.layout.card.flip',
  'fx.layout.card.pop',
  'fx.layout.card.reveal',
  'fx.layout.card.scroll',
  'fx.layout.card.scrollcover',
  'fx.layout.card.scrollreveal',
  'fx.layout.card.slide',
  'grid.filter.boolean',
  'grid.filter.date',
  'grid.filter.list',
  'grid.filter.number', 'grid.filter.numeric',
  'grid.filter.number', 'grid.filter.numeric',
  'grid.filter.string',
  'layout.absolute',
  'layout.accordion',
  'layout.anchor',
  'layout.autocomponent',
  'layout.auto', 'layout.autocontainer',
  'layout.auto', 'layout.autocontainer',
  'layout.body',
  'layout.body',
  'layout.border',
  'layout.boundlist',
  'layout.box',
  'layout.card',
  'layout.center',
  'layout.checkboxgroup',
  'layout.checkboxgroup',
  'layout.column',
  'layout.column',
  'layout.columncomponent',
  'layout.container',
  'layout.dashboard',
  'layout.dock',
  'layout.editor',
  'layout.fieldcontainer',
  'layout.fieldset',
  'layout.fieldset',
  'layout.fit',
  'layout.form',
  'layout.gridcolumn',
  'layout.hbox',
  'layout.htmleditor',
  'layout.htmleditor',
  'layout.progressbar',
  'layout.progressbar',
  'layout.segmentedbutton',
  'layout.table',
  'layout.table',
  'layout.tableview',
  'layout.tableview',
  'layout.ux.center',
  'layout.vbox',
  'namer.default',
  'part.part',
  'plugin.bufferedrenderer',
  'plugin.cellediting',
  'plugin.gridfilters',
  'plugin.gridheaderreorderer',
  'plugin.gridheaderresizer',
  'plugin.gridviewdragdrop',
  'plugin.responsive',
  'plugin.rowediting',
  'plugin.rowexpander',
  'plugin.treeviewdragdrop',
  'plugin.viewport',
  'proxy.ajax',
  'proxy.direct',
  'proxy.jsonp', 'proxy.scripttag',
  'proxy.jsonp', 'proxy.scripttag',
  'proxy.localstorage',
  'proxy.memory',
  'proxy.proxy',
  'proxy.rest',
  'proxy.server',
  'proxy.sessionstorage',
  'proxy.sql',
  'reader.array',
  'reader.base',
  'reader.json',
  'reader.xml',
  'schema.default',
  'selection.cellmodel',
  'selection.checkboxmodel',
  'selection.rowmodel',
  'selection.treemodel',
  'state.localstorage',
  'store.array',
  'store.buffered',
  'store.chained',
  'store.direct',
  'store.json',
  'store.jsonp',
  'store.node',
  'store.store',
  'store.tree',
  'store.xml',
  'trigger.component',
  'trigger.spinner',
  'trigger.trigger',
  'viewmodel.default',
  'view.navigation.boundlist',
  'view.navigation.default',
  'view.navigation.grid',
  'view.navigation.tree',
  'widget.actioncolumn',
  'widget.actioncolumn',
  'widget.bindinspector-componentdetail',
  'widget.bindinspector-componentlist',
  'widget.bindinspector-container',
  'widget.bindinspector-viewmodeldetail',
  'widget.booleancolumn',
  'widget.booleancolumn',
  'widget.bordersplitter',
  'widget.boundlist',
  'widget.breadcrumb',
  'widget.button',
  'widget.buttongroup',
  'widget.checkbox',
  'widget.checkboxfield',
  'widget.checkboxfield', 'widget.checkbox',
  'widget.checkboxfield', 'widget.checkbox',
  'widget.checkboxgroup',
  'widget.checkcolumn',
  'widget.colormenu',
  'widget.colorpicker',
  'widget.colorpicker',
  'widget.columnsplitter',
  'widget.columnsplitter',
  'widget.combobox', 'widget.combo',
  'widget.combobox', 'widget.combo',
  'widget.component',
  'widget.container',
  'widget.cycle',
  'widget.dashboard',
  'widget.dashboard-column',
  'widget.dashboard-panel',
  'widget.dataview',
  'widget.datecolumn',
  'widget.datecolumn',
  'widget.datefield',
  'widget.datemenu',
  'widget.datepicker',
  'widget.datepicker',
  'widget.displayfield',
  'widget.editor',
  'widget.field',
  'widget.fieldcontainer',
  'widget.fieldset',
  'widget.filebutton',
  'widget.filefield', 'widget.fileuploadfield',
  'widget.filefield', 'widget.fileuploadfield',
  'widget.flash',
  'widget.form',
  'widget.grid',
  'widget.gridcolumn',
  'widget.gridpanel',
  'widget.gridpanel', 'widget.grid',
  'widget.gridpanel', 'widget.grid',
  'widget.gridview',
  'widget.header',
  'widget.headercontainer',
  'widget.hiddenfield', 'widget.hidden',
  'widget.hiddenfield', 'widget.hidden',
  'widget.htmleditor',
  'widget.image', 'widget.imagecomponent',
  'widget.image', 'widget.imagecomponent',
  'widget.label',
  'widget.loadmask',
  'widget.menu',
  'widget.menu',
  'widget.menucheckitem',
  'widget.menuitem',
  'widget.menuseparator',
  'widget.menuseparator',
  'widget.messagebox',
  'widget.monthpicker',
  'widget.multiselector',
  'widget.multiselector-search',
  'widget.multislider',
  'widget.numbercolumn',
  'widget.numbercolumn',
  'widget.numberfield',
  'widget.pagingtoolbar',
  'widget.panel',
  'widget.pickerfield',
  'widget.progressbar',
  'widget.progressbarwidget',
  'widget.propertygrid',
  'widget.quicktip',
  'widget.radiofield', 'widget.radio',
  'widget.radiofield', 'widget.radio',
  'widget.radiogroup',
  'widget.roweditor',
  'widget.roweditorbuttons',
  'widget.rownumberer',
  'widget.segmentedbutton',
  'widget.slidertip',
  'widget.sliderwidget',
  'widget.slider', 'widget.sliderfield',
  'widget.slider', 'widget.sliderfield',
  'widget.sparklinebar',
  'widget.sparklinebox',
  'widget.sparklinebullet',
  'widget.sparklinediscrete',
  'widget.sparklineline',
  'widget.sparklinepie',
  'widget.sparklinetristate',
  'widget.spinnerfield',
  'widget.splitbutton',
  'widget.splitter',
  'widget.splitter',
  'widget.tab',
  'widget.tabbar',
  'widget.tablepanel',
  'widget.tableview',
  'widget.tabpanel',
  'widget.tagfield',
  'widget.tbfill',
  'widget.tbitem',
  'widget.tbseparator',
  'widget.tbspacer',
  'widget.tbtext',
  'widget.templatecolumn',
  'widget.templatecolumn',
  'widget.textareafield', 'widget.textarea',
  'widget.textareafield', 'widget.textarea',
  'widget.textfield',
  'widget.timefield',
  'widget.timepicker',
  'widget.tip',
  'widget.title',
  'widget.toast',
  'widget.tool',
  'widget.toolbar',
  'widget.tooltip',
  'widget.treecolumn',
  'widget.treepanel',
  'widget.treeview',
  'widget.triggerfield', 'widget.trigger',
  'widget.triggerfield', 'widget.trigger',
  'widget.viewport',
  'widget.widget',
  'widget.widgetcolumn',
  'widget.window',
  'writer.base',
  'writer.json',
  'writer.xml',

);


?>

